power<-read.table("C:/Users/binay/OneDrive/Desktop/courseproject1/household_power_consumption.txt",header = TRUE,sep=";")
subpower<-subset(power,power$Date=="1/2/2007"|power$Date=="2/2/2007")
class(subpower$Date)
subpower$Date<-as.Date(subpower$Date,format = "%m/%d/%Y")
subpower$Time<-strptime(subpower$Time,format = "%H:%M:%S")
subpower[1:1440,c("Time")]<- format(subpower[1:1440,c("Time")],"2007-02-01 %H:%M:%S")
subpower[1441:2880,c("Time")]<-format(subpower[1441:2880,c("Time")],"2007-02-02 %H:%M:%S")
plot(subpower$Time,subpower$Sub_metering_1,type = "n",xlab = "",ylab = "Energy sub metering")
with(subpower,lines(subpower$Time,as.numeric(as.character(subpower$Sub_metering_1))))
with(subpower,lines(subpower$Time,as.numeric(as.character(subpower$Sub_metering_2)),col="red"))
with(subpower,lines(subpower$Time,as.numeric(as.character(subpower$Sub_metering_3)),col="blue"))
legend("topright",lty=1,col = c("blue","black","red"), legend = c("Sub_metering_3","Sub_metering_1","Sub_metering_2"))
title(main = "plot3")